/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _demoplaysavedata_h_
#define _demoplaysavedata_h_
//---------------------------------------------------------------------------------
extern const unsigned char demoplaysavedata[];
extern const int demoplaysavedata_size;
//---------------------------------------------------------------------------------
#endif //_demoplaysavedata_h_
//---------------------------------------------------------------------------------
